
create table peoplehalf1 (
	id INT NOT NULL ,
	first_name VARCHAR(50),
	gender VARCHAR(90),
	country VARCHAR(50),
	race VARCHAR(50),
	PRIMARY KEY(id)
);

insert into peoplehalf1 (id, first_name, gender, country, race) values (1, 'Charlotte', 'Female', 'Slovenia', 'Ottawa');
insert into peoplehalf1 (id, first_name, gender, country, race) values (2, 'Dudley', 'Male', 'China', 'Fijian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (3, 'Tony', 'Polygender', 'Argentina', 'Choctaw');
insert into peoplehalf1 (id, first_name, gender, country, race) values (4, 'Lindsey', 'Female', 'Indonesia', 'Cheyenne');
insert into peoplehalf1 (id, first_name, gender, country, race) values (5, 'Maudie', 'Female', 'Ukraine', 'Delaware');
insert into peoplehalf1 (id, first_name, gender, country, race) values (6, 'Charmine', 'Female', 'Nigeria', 'Venezuelan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (7, 'Agnese', 'Genderfluid', 'Brazil', 'Shoshone');
insert into peoplehalf1 (id, first_name, gender, country, race) values (8, 'Urban', 'Male', 'Uruguay', 'Nicaraguan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (9, 'Dolf', 'Male', 'Tanzania', 'Peruvian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (10, 'Laird', 'Male', 'Tajikistan', 'Black or African American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (11, 'Whitaker', 'Genderqueer', 'Ukraine', 'Tongan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (12, 'Abe', 'Male', 'Guinea', 'Pima');
insert into peoplehalf1 (id, first_name, gender, country, race) values (13, 'Boris', 'Male', 'Philippines', 'Hmong');
insert into peoplehalf1 (id, first_name, gender, country, race) values (14, 'Beverie', 'Female', 'Czech Republic', 'Comanche');
insert into peoplehalf1 (id, first_name, gender, country, race) values (15, 'Janeva', 'Female', 'Armenia', 'Panamanian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (16, 'Aloise', 'Female', 'China', 'Iroquois');
insert into peoplehalf1 (id, first_name, gender, country, race) values (17, 'Roanna', 'Female', 'Indonesia', 'Seminole');
insert into peoplehalf1 (id, first_name, gender, country, race) values (18, 'Meridel', 'Genderqueer', 'France', 'Blackfeet');
insert into peoplehalf1 (id, first_name, gender, country, race) values (19, 'Grantley', 'Male', 'Sweden', 'Nicaraguan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (20, 'Godfry', 'Male', 'United States', 'Indonesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (21, 'Artur', 'Male', 'Russia', 'Delaware');
insert into peoplehalf1 (id, first_name, gender, country, race) values (22, 'Christoph', 'Male', 'Thailand', 'Bangladeshi');
insert into peoplehalf1 (id, first_name, gender, country, race) values (23, 'Cordy', 'Genderqueer', 'China', 'Tohono O''Odham');
insert into peoplehalf1 (id, first_name, gender, country, race) values (24, 'Hurleigh', 'Male', 'Indonesia', 'Pueblo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (25, 'Dacie', 'Female', 'Sweden', 'Thai');
insert into peoplehalf1 (id, first_name, gender, country, race) values (26, 'Huntlee', 'Male', 'China', 'Bolivian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (27, 'Raquel', 'Female', 'Yemen', 'American Indian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (28, 'Ezmeralda', 'Female', 'Russia', 'Indonesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (29, 'Bridget', 'Female', 'China', 'Guatemalan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (30, 'Alexis', 'Female', 'Indonesia', 'Crow');
insert into peoplehalf1 (id, first_name, gender, country, race) values (31, 'Nevile', 'Agender', 'Canada', 'Pima');
insert into peoplehalf1 (id, first_name, gender, country, race) values (32, 'Billy', 'Male', 'Japan', 'Choctaw');
insert into peoplehalf1 (id, first_name, gender, country, race) values (33, 'Sileas', 'Female', 'United States', 'Aleut');
insert into peoplehalf1 (id, first_name, gender, country, race) values (34, 'Man', 'Male', 'Brazil', 'Central American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (35, 'Perle', 'Female', 'China', 'Native Hawaiian and Other Pacific Islander (NHPI)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (36, 'Northrup', 'Male', 'Japan', 'American Indian and Alaska Native (AIAN)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (37, 'Coralie', 'Female', 'Indonesia', 'Sri Lankan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (38, 'Cyrill', 'Male', 'Cyprus', 'Native Hawaiian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (39, 'Katee', 'Female', 'Philippines', 'Latin American Indian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (40, 'Analise', 'Female', 'Poland', 'Melanesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (41, 'Mari', 'Female', 'China', 'Osage');
insert into peoplehalf1 (id, first_name, gender, country, race) values (42, 'Geri', 'Female', 'China', 'Laotian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (43, 'Stepha', 'Female', 'China', 'Cambodian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (44, 'Carola', 'Female', 'Morocco', 'Comanche');
insert into peoplehalf1 (id, first_name, gender, country, race) values (45, 'Willem', 'Bigender', 'Philippines', 'Puerto Rican');
insert into peoplehalf1 (id, first_name, gender, country, race) values (46, 'Davie', 'Male', 'Poland', 'Tongan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (47, 'Esta', 'Female', 'Kiribati', 'Black or African American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (48, 'Morty', 'Male', 'Kyrgyzstan', 'Polynesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (49, 'Anthiathia', 'Agender', 'China', 'Native Hawaiian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (50, 'Madelena', 'Female', 'China', 'Native Hawaiian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (51, 'Rainer', 'Male', 'Brazil', 'Uruguayan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (52, 'Shena', 'Female', 'Portugal', 'Shoshone');
insert into peoplehalf1 (id, first_name, gender, country, race) values (53, 'Franciskus', 'Genderfluid', 'Czech Republic', 'Creek');
insert into peoplehalf1 (id, first_name, gender, country, race) values (54, 'Tatiania', 'Female', 'Sierra Leone', 'Melanesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (55, 'Jenn', 'Female', 'China', 'Shoshone');
insert into peoplehalf1 (id, first_name, gender, country, race) values (56, 'Tine', 'Female', 'China', 'Navajo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (57, 'Brody', 'Male', 'Sweden', 'South American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (58, 'Corenda', 'Non-binary', 'Palestinian Territory', 'Shoshone');
insert into peoplehalf1 (id, first_name, gender, country, race) values (59, 'Lucius', 'Male', 'Portugal', 'Vietnamese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (60, 'Ricardo', 'Male', 'Mali', 'Aleut');
insert into peoplehalf1 (id, first_name, gender, country, race) values (61, 'Ravi', 'Male', 'Philippines', 'Micronesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (62, 'Jemima', 'Female', 'Portugal', 'Latin American Indian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (63, 'Duky', 'Male', 'China', 'Ecuadorian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (64, 'Jermaine', 'Female', 'Argentina', 'Nicaraguan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (65, 'Steven', 'Male', 'Iran', 'Alaska Native');
insert into peoplehalf1 (id, first_name, gender, country, race) values (66, 'Charin', 'Female', 'Brazil', 'Bangladeshi');
insert into peoplehalf1 (id, first_name, gender, country, race) values (67, 'Marcelo', 'Male', 'Brazil', 'Pima');
insert into peoplehalf1 (id, first_name, gender, country, race) values (68, 'Jania', 'Female', 'China', 'Pima');
insert into peoplehalf1 (id, first_name, gender, country, race) values (69, 'Lora', 'Female', 'Argentina', 'Vietnamese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (70, 'Rogers', 'Male', 'Tanzania', 'Honduran');
insert into peoplehalf1 (id, first_name, gender, country, race) values (71, 'Zelda', 'Female', 'Armenia', 'Taiwanese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (72, 'Gina', 'Bigender', 'Philippines', 'Bangladeshi');
insert into peoplehalf1 (id, first_name, gender, country, race) values (73, 'Aguste', 'Male', 'Russia', 'Argentinian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (74, 'Modestia', 'Female', 'China', 'Comanche');
insert into peoplehalf1 (id, first_name, gender, country, race) values (75, 'Inga', 'Female', 'Greece', 'Vietnamese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (76, 'Annabela', 'Female', 'Indonesia', 'Bolivian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (77, 'Randolph', 'Male', 'Estonia', 'Fijian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (78, 'Brana', 'Female', 'Malta', 'Chamorro');
insert into peoplehalf1 (id, first_name, gender, country, race) values (79, 'Danna', 'Female', 'Thailand', 'Uruguayan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (80, 'Zaneta', 'Female', 'Georgia', 'Taiwanese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (81, 'Anestassia', 'Female', 'Croatia', 'Aleut');
insert into peoplehalf1 (id, first_name, gender, country, race) values (82, 'Adolphe', 'Male', 'Palestinian Territory', 'Iroquois');
insert into peoplehalf1 (id, first_name, gender, country, race) values (83, 'Melisenda', 'Female', 'Germany', 'Central American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (84, 'Gunner', 'Male', 'Sweden', 'Pueblo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (85, 'Ranique', 'Female', 'Russia', 'Chamorro');
insert into peoplehalf1 (id, first_name, gender, country, race) values (86, 'Zack', 'Male', 'Philippines', 'Pueblo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (87, 'Shanda', 'Female', 'United States', 'Potawatomi');
insert into peoplehalf1 (id, first_name, gender, country, race) values (88, 'Roman', 'Male', 'Jamaica', 'Salvadoran');
insert into peoplehalf1 (id, first_name, gender, country, race) values (89, 'Willie', 'Female', 'Nigeria', 'Polynesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (90, 'Reinaldo', 'Male', 'Czech Republic', 'Choctaw');
insert into peoplehalf1 (id, first_name, gender, country, race) values (91, 'Garry', 'Male', 'China', 'Central American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (92, 'Murial', 'Female', 'Nigeria', 'Pueblo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (93, 'Stanislaw', 'Male', 'Nigeria', 'Puget Sound Salish');
insert into peoplehalf1 (id, first_name, gender, country, race) values (94, 'Daile', 'Female', 'Colombia', 'South American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (95, 'Travers', 'Genderfluid', 'Honduras', 'Yuman');
insert into peoplehalf1 (id, first_name, gender, country, race) values (96, 'Ware', 'Male', 'Indonesia', 'Ecuadorian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (97, 'Therese', 'Female', 'Costa Rica', 'Salvadoran');
insert into peoplehalf1 (id, first_name, gender, country, race) values (98, 'Mayne', 'Male', 'France', 'Puerto Rican');
insert into peoplehalf1 (id, first_name, gender, country, race) values (99, 'Billi', 'Female', 'Indonesia', 'Comanche');
insert into peoplehalf1 (id, first_name, gender, country, race) values (100, 'Chuck', 'Male', 'France', 'Filipino');
insert into peoplehalf1 (id, first_name, gender, country, race) values (101, 'Corrine', 'Female', 'Brazil', 'Salvadoran');
insert into peoplehalf1 (id, first_name, gender, country, race) values (102, 'Lusa', 'Female', 'Russia', 'American Indian and Alaska Native (AIAN)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (103, 'Adriane', 'Female', 'Russia', 'Lumbee');
insert into peoplehalf1 (id, first_name, gender, country, race) values (104, 'Rip', 'Male', 'Belarus', 'Mexican');
insert into peoplehalf1 (id, first_name, gender, country, race) values (105, 'Juline', 'Female', 'Russia', 'Apache');
insert into peoplehalf1 (id, first_name, gender, country, race) values (106, 'Ivonne', 'Female', 'Israel', 'Sri Lankan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (107, 'Patric', 'Male', 'Russia', 'Delaware');
insert into peoplehalf1 (id, first_name, gender, country, race) values (108, 'Flem', 'Male', 'Brazil', 'Comanche');
insert into peoplehalf1 (id, first_name, gender, country, race) values (109, 'Conni', 'Female', 'Serbia', 'Chamorro');
insert into peoplehalf1 (id, first_name, gender, country, race) values (110, 'Sammy', 'Male', 'China', 'Guatemalan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (111, 'Branden', 'Male', 'China', 'Dominican (Dominican Republic)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (112, 'Daile', 'Female', 'Turkmenistan', 'Vietnamese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (113, 'Erika', 'Female', 'Burkina Faso', 'White');
insert into peoplehalf1 (id, first_name, gender, country, race) values (114, 'Perrine', 'Female', 'China', 'Kiowa');
insert into peoplehalf1 (id, first_name, gender, country, race) values (115, 'Shauna', 'Female', 'Palestinian Territory', 'Black or African American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (116, 'Parsifal', 'Male', 'Indonesia', 'Uruguayan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (117, 'Annaliese', 'Female', 'China', 'Osage');
insert into peoplehalf1 (id, first_name, gender, country, race) values (118, 'Denney', 'Male', 'Slovenia', 'Ottawa');
insert into peoplehalf1 (id, first_name, gender, country, race) values (119, 'Dael', 'Female', 'Russia', 'Chickasaw');
insert into peoplehalf1 (id, first_name, gender, country, race) values (120, 'Geoff', 'Male', 'Sweden', 'Colombian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (121, 'Donella', 'Female', 'Poland', 'Japanese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (122, 'Conrad', 'Male', 'Indonesia', 'White');
insert into peoplehalf1 (id, first_name, gender, country, race) values (123, 'Judy', 'Female', 'Indonesia', 'Guamanian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (124, 'Archaimbaud', 'Male', 'Madagascar', 'Pima');
insert into peoplehalf1 (id, first_name, gender, country, race) values (125, 'Nero', 'Male', 'South Africa', 'Filipino');
insert into peoplehalf1 (id, first_name, gender, country, race) values (126, 'Sherlocke', 'Agender', 'Argentina', 'Tongan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (127, 'Noby', 'Male', 'Kenya', 'White');
insert into peoplehalf1 (id, first_name, gender, country, race) values (128, 'Teresina', 'Female', 'China', 'Pueblo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (129, 'Donni', 'Genderfluid', 'Indonesia', 'Black or African American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (130, 'Becki', 'Female', 'Poland', 'Cambodian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (131, 'Rufus', 'Male', 'Poland', 'South American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (132, 'Lucille', 'Bigender', 'Portugal', 'Paraguayan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (133, 'Gordan', 'Male', 'Finland', 'White');
insert into peoplehalf1 (id, first_name, gender, country, race) values (134, 'Binnie', 'Female', 'China', 'South American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (135, 'Hyacinth', 'Female', 'Russia', 'Lumbee');
insert into peoplehalf1 (id, first_name, gender, country, race) values (136, 'Sanderson', 'Male', 'United Arab Emirates', 'Blackfeet');
insert into peoplehalf1 (id, first_name, gender, country, race) values (137, 'Pollyanna', 'Female', 'Ukraine', 'Tlingit-Haida');
insert into peoplehalf1 (id, first_name, gender, country, race) values (138, 'Kyrstin', 'Female', 'Indonesia', 'Yuman');
insert into peoplehalf1 (id, first_name, gender, country, race) values (139, 'Harriett', 'Genderfluid', 'Croatia', 'Cuban');
insert into peoplehalf1 (id, first_name, gender, country, race) values (140, 'Bradan', 'Male', 'Indonesia', 'Native Hawaiian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (141, 'Lenka', 'Non-binary', 'China', 'Cheyenne');
insert into peoplehalf1 (id, first_name, gender, country, race) values (142, 'Ailbert', 'Genderfluid', 'Argentina', 'American Indian and Alaska Native (AIAN)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (143, 'Mercedes', 'Female', 'Indonesia', 'Potawatomi');
insert into peoplehalf1 (id, first_name, gender, country, race) values (144, 'Roseline', 'Female', 'Moldova', 'Chinese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (145, 'Patrizio', 'Male', 'Yemen', 'Central American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (146, 'Sheffie', 'Male', 'Iran', 'Delaware');
insert into peoplehalf1 (id, first_name, gender, country, race) values (147, 'Pebrook', 'Male', 'Portugal', 'Puget Sound Salish');
insert into peoplehalf1 (id, first_name, gender, country, race) values (148, 'Myrwyn', 'Male', 'Democratic Republic of the Congo', 'Yaqui');
insert into peoplehalf1 (id, first_name, gender, country, race) values (149, 'Ricki', 'Male', 'China', 'Argentinian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (150, 'Lela', 'Female', 'Nigeria', 'Tlingit-Haida');
insert into peoplehalf1 (id, first_name, gender, country, race) values (151, 'Sherman', 'Male', 'Guinea', 'Asian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (152, 'Tandie', 'Agender', 'France', 'Potawatomi');
insert into peoplehalf1 (id, first_name, gender, country, race) values (153, 'Noam', 'Male', 'Indonesia', 'Cuban');
insert into peoplehalf1 (id, first_name, gender, country, race) values (154, 'Radcliffe', 'Male', 'China', 'Cherokee');
insert into peoplehalf1 (id, first_name, gender, country, race) values (155, 'Wilbert', 'Male', 'Portugal', 'Navajo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (156, 'Cheri', 'Female', 'Guatemala', 'American Indian and Alaska Native (AIAN)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (157, 'Gabi', 'Male', 'Thailand', 'Central American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (158, 'Mylo', 'Male', 'China', 'Melanesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (159, 'Alasdair', 'Polygender', 'China', 'Guamanian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (160, 'Magda', 'Female', 'China', 'Sri Lankan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (161, 'Annabella', 'Female', 'Indonesia', 'Sioux');
insert into peoplehalf1 (id, first_name, gender, country, race) values (162, 'Jud', 'Male', 'Bulgaria', 'Fijian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (163, 'Quincey', 'Non-binary', 'Montenegro', 'Malaysian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (164, 'Shermie', 'Male', 'China', 'Comanche');
insert into peoplehalf1 (id, first_name, gender, country, race) values (165, 'Cleveland', 'Male', 'Finland', 'Osage');
insert into peoplehalf1 (id, first_name, gender, country, race) values (166, 'Pip', 'Male', 'France', 'Taiwanese');
insert into peoplehalf1 (id, first_name, gender, country, race) values (167, 'Madlin', 'Female', 'Jordan', 'Salvadoran');
insert into peoplehalf1 (id, first_name, gender, country, race) values (168, 'Schuyler', 'Male', 'France', 'Paraguayan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (169, 'Bryce', 'Male', 'Indonesia', 'Korean');
insert into peoplehalf1 (id, first_name, gender, country, race) values (170, 'Damon', 'Male', 'Tanzania', 'Native Hawaiian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (171, 'Cassi', 'Female', 'Ukraine', 'Cambodian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (172, 'Charlton', 'Male', 'Russia', 'Navajo');
insert into peoplehalf1 (id, first_name, gender, country, race) values (173, 'Thorin', 'Male', 'China', 'Venezuelan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (174, 'Whitby', 'Male', 'Mexico', 'Cambodian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (175, 'Thadeus', 'Male', 'Thailand', 'Samoan');
insert into peoplehalf1 (id, first_name, gender, country, race) values (176, 'Hew', 'Polygender', 'Indonesia', 'Yaqui');
insert into peoplehalf1 (id, first_name, gender, country, race) values (177, 'Sondra', 'Female', 'Brazil', 'Filipino');
insert into peoplehalf1 (id, first_name, gender, country, race) values (178, 'Bearnard', 'Male', 'China', 'American Indian and Alaska Native (AIAN)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (179, 'Anders', 'Male', 'Philippines', 'Paiute');
insert into peoplehalf1 (id, first_name, gender, country, race) values (180, 'Jeno', 'Male', 'Russia', 'Yaqui');
insert into peoplehalf1 (id, first_name, gender, country, race) values (181, 'Bertha', 'Female', 'China', 'Lumbee');
insert into peoplehalf1 (id, first_name, gender, country, race) values (182, 'Gael', 'Female', 'Greece', 'Tohono O''Odham');
insert into peoplehalf1 (id, first_name, gender, country, race) values (183, 'Tamas', 'Male', 'Portugal', 'Black or African American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (184, 'Gerek', 'Male', 'Poland', 'Paiute');
insert into peoplehalf1 (id, first_name, gender, country, race) values (185, 'Kale', 'Male', 'Slovenia', 'Kiowa');
insert into peoplehalf1 (id, first_name, gender, country, race) values (186, 'Beverlie', 'Female', 'Peru', 'Malaysian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (187, 'Elsey', 'Female', 'Greece', 'American Indian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (188, 'Kellie', 'Female', 'United States', 'Native Hawaiian and Other Pacific Islander (NHPI)');
insert into peoplehalf1 (id, first_name, gender, country, race) values (189, 'Ford', 'Male', 'Burkina Faso', 'Houma');
insert into peoplehalf1 (id, first_name, gender, country, race) values (190, 'Deb', 'Female', 'Guatemala', 'Micronesian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (191, 'Wye', 'Male', 'Burkina Faso', 'Menominee');
insert into peoplehalf1 (id, first_name, gender, country, race) values (192, 'Jasun', 'Male', 'Indonesia', 'South American');
insert into peoplehalf1 (id, first_name, gender, country, race) values (193, 'Delainey', 'Male', 'Portugal', 'Costa Rican');
insert into peoplehalf1 (id, first_name, gender, country, race) values (194, 'Farleigh', 'Male', 'Brazil', 'Seminole');
insert into peoplehalf1 (id, first_name, gender, country, race) values (195, 'Toddie', 'Male', 'Argentina', 'Malaysian');
insert into peoplehalf1 (id, first_name, gender, country, race) values (196, 'Simonette', 'Female', 'Indonesia', 'Houma');
insert into peoplehalf1 (id, first_name, gender, country, race) values (197, 'Georgena', 'Female', 'Norway', 'Crow');
insert into peoplehalf1 (id, first_name, gender, country, race) values (198, 'Caitlin', 'Female', 'Indonesia', 'Creek');
insert into peoplehalf1 (id, first_name, gender, country, race) values (199, 'Lavina', 'Female', 'Indonesia', 'Houma');
insert into peoplehalf1 (id, first_name, gender, country, race) values (200, 'Gibb', 'Male', 'China', 'Pima');

SELECT first_name FROM peoplehalf1 WHERE EXISTS (SELECT first_name FROM peoplehalf1 WHERE first_name = 'Toddie');